name: instagram_clone
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animator: ^2.0.1
  intl: ^0.16.1

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.8.1

  provider: ^4.0.3

  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.1
  firebase_storage: ^3.1.1

  cached_network_image: ^2.0.0
  image_picker: ^0.6.3+1
  uuid: ^2.0.4
  path_provider: ^1.6.0
  flutter_image_compress: ^0.6.5+1

  image_cropper: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/images/


  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
